{
  "jobs": [
    {
      "primaryCustomerId": 56,
      "primaryCustomerCode": "3MI0054",
      "customerId": 56,
      "customerCode": "3MI0054",
      "customerName": "3M/IATD Division Engineering",
      "jobId": 1071,
      "jobNumber": "0001072-1",
      "taskId": 1650,
      "jobSubmittedDtm": "2016-06-21T11:20:00",
      "jobCompletedDtm": null,
      "jobScheduledDtm": "2016-06-21T17:21:00",
      "workOrderId": 1089,
      "workOrderTypeId": 3,
      "workOrderTypeCode": "CALLIN",
      "workOrderTypeText": "Customer Called in",
      "machineId": 6,
      "machineSerialNumber": "0004361",
      "machineUnitId": "",
      "machineLocation": "",
      "machineDescription": "40,000lb x 5lb",
      "modelId": 4,
      "modelClass": "Rice Lake",
      "modelNumber": "RL 480",
      "modelDescription": "",
      "jobTypeId": 5,
      "jobTypeCode": "REP",
      "jobTypeText": "Repair",
      "jobPriorityId": 10,
      "jobPriorityText": "Medium",
      "contractId": null,
      "contractTypeId": "",
      "contractTypeText": "",
      "jobCommentText": "test test",
      "jobIsOpen": true,
      "jobWorkPerformed": null,
      "jobPoNumber": "",
      "jobPmDue": false,
      "jobPmPerformed": false,
      "technicianId": 64002,
      "technicianCode": "74500",
      "technicianName": "Chris Gutierrez",
      "technicianPhone": null,
      "technicianEmail": "xx.com",
      "technicianAssignedDtm": "2016-06-21T17:21:00",
      "requesterId": 0,
      "requesterTitle": null,
      "requesterFirstName": null,
      "requesterMiddleInitial": null,
      "requesterLastName": null,
      "requesterPhone": null,
      "requesterPhoneExtension": null,
      "requesterPhoneOther": null,
      "requesterEmail": null,
      "jobStatusId": 0,
      "jobStatusText": null,
      "taskStatusId": 1,
      "taskStatusText": "Open",
      "taskIsOpen": true,
      "jobEttr": 0.0,
      "jobIsEstimated": false,
      "resolutionCodeId": 0,
      "resolutionCodeText": null
    },
    {
      "primaryCustomerId": 293,
      "primaryCustomerCode": "PEN0291",
      "customerId": 293,
      "customerCode": "PEN0291",
      "customerName": "Pentagon Freight",
      "jobId": 1070,
      "jobNumber": "0001071-1",
      "taskId": 1649,
      "jobSubmittedDtm": "2016-06-10T09:48:00",
      "jobCompletedDtm": null,
      "jobScheduledDtm": "2016-06-10T15:48:00",
      "workOrderId": 1088,
      "workOrderTypeId": 3,
      "workOrderTypeCode": "CALLIN",
      "workOrderTypeText": "Customer Called in",
      "machineId": 89,
      "machineSerialNumber": "175311",
      "machineUnitId": "Yard",
      "machineLocation": "Yard",
      "machineDescription": "30,000lb x 5lb",
      "modelId": 2,
      "modelClass": "Rice Lake",
      "modelNumber": "355",
      "modelDescription": "",
      "jobTypeId": 5,
      "jobTypeCode": "REP",
      "jobTypeText": "Repair",
      "jobPriorityId": 10,
      "jobPriorityText": "Medium",
      "contractId": null,
      "contractTypeId": "",
      "contractTypeText": "",
      "jobCommentText": "yard scale drifting",
      "jobIsOpen": true,
      "jobWorkPerformed": null,
      "jobPoNumber": null,
      "jobPmDue": false,
      "jobPmPerformed": false,
      "technicianId": 64006,
      "technicianCode": "RD",
      "technicianName": "Robert Detuncq",
      "technicianPhone": null,
      "technicianEmail": "xx.com",
      "technicianAssignedDtm": "2016-06-10T15:48:00",
      "requesterId": 22,
      "requesterTitle": null,
      "requesterFirstName": "Scott",
      "requesterMiddleInitial": null,
      "requesterLastName": "Stone",
      "requesterPhone": "7133029700",
      "requesterPhoneExtension": null,
      "requesterPhoneOther": null,
      "requesterEmail": "xx.com",
      "jobStatusId": 0,
      "jobStatusText": null,
      "taskStatusId": 1,
      "taskStatusText": "Open",
      "taskIsOpen": true,
      "jobEttr": 2.0,
      "jobIsEstimated": false,
      "resolutionCodeId": 0,
      "resolutionCodeText": null
    },
    {
      "primaryCustomerId": 611,
      "primaryCustomerCode": "COA0615",
      "customerId": 611,
      "customerCode": "COA0615",
      "customerName": "Coastal Mechanics Co. Inc",
      "jobId": 1069,
      "jobNumber": "0001070-1",
      "taskId": 1648,
      "jobSubmittedDtm": "2016-06-10T08:46:00",
      "jobCompletedDtm": "2016-06-01T11:54:00",
      "jobScheduledDtm": "2016-06-10T14:46:00",
      "workOrderId": 1087,
      "workOrderTypeId": 3,
      "workOrderTypeCode": "CALLIN",
      "workOrderTypeText": "Customer Called in",
      "machineId": 2698,
      "machineSerialNumber": "17669000085",
      "machineUnitId": "",
      "machineLocation": "",
      "machineDescription": "Aircraft Scale",
      "modelId": 9,
      "modelClass": "Rice Lake",
      "modelNumber": "920i",
      "modelDescription": "",
      "jobTypeId": 2,
      "jobTypeCode": "Insta",
      "jobTypeText": "Installation",
      "jobPriorityId": 10,
      "jobPriorityText": "Medium",
      "contractId": null,
      "contractTypeId": "",
      "contractTypeText": "",
      "jobCommentText": "Install new indicator",
      "jobIsOpen": true,
      "jobWorkPerformed": null,
      "jobPoNumber": "CC",
      "jobPmDue": false,
      "jobPmPerformed": false,
      "technicianId": 64006,
      "technicianCode": "RD",
      "technicianName": "Robert Detuncq",
      "technicianPhone": null,
      "technicianEmail": "xx.com",
      "technicianAssignedDtm": "2016-06-10T08:54:00",
      "requesterId": 786,
      "requesterTitle": null,
      "requesterFirstName": "Gregg",
      "requesterMiddleInitial": null,
      "requesterLastName": "Czubik",
      "requesterPhone": null,
      "requesterPhoneExtension": null,
      "requesterPhoneOther": null,
      "requesterEmail": "xx.com",
      "jobStatusId": 0,
      "jobStatusText": null,
      "taskStatusId": 1,
      "taskStatusText": "Open",
      "taskIsOpen": true,
      "jobEttr": 1.0,
      "jobIsEstimated": false,
      "resolutionCodeId": 0,
      "resolutionCodeText": null
    },
    {
      "primaryCustomerId": 137,
      "primaryCustomerCode": "CON0135",
      "customerId": 137,
      "customerCode": "CON0135",
      "customerName": "CST Perfomance Products Corp",
      "jobId": 1068,
      "jobNumber": "0001069-1",
      "taskId": 1645,
      "jobSubmittedDtm": "2016-06-10T08:10:00",
      "jobCompletedDtm": null,
      "jobScheduledDtm": "2016-06-10T14:10:00",
      "workOrderId": 1086,
      "workOrderTypeId": 3,
      "workOrderTypeCode": "CALLIN",
      "workOrderTypeText": "Customer Called in",
      "machineId": 134,
      "machineSerialNumber": "47672",
      "machineUnitId": "",
      "machineLocation": "K1",
      "machineDescription": "",
      "modelId": 15,
      "modelClass": "GSE",
      "modelNumber": "350",
      "modelDescription": "",
      "jobTypeId": 5,
      "jobTypeCode": "REP",
      "jobTypeText": "Repair",
      "jobPriorityId": 10,
      "jobPriorityText": "Medium",
      "contractId": null,
      "contractTypeId": "",
      "contractTypeText": "",
      "jobCommentText": "Calibrate K1,  Look at floor scale",
      "jobIsOpen": true,
      "jobWorkPerformed": null,
      "jobPoNumber": null,
      "jobPmDue": true,
      "jobPmPerformed": false,
      "technicianId": 64001,
      "technicianCode": "71019",
      "technicianName": "Melvin Jefferies",
      "technicianPhone": null,
      "technicianEmail": "xx.com",
      "technicianAssignedDtm": "2016-06-10T14:10:00",
      "requesterId": 21,
      "requesterTitle": null,
      "requesterFirstName": "Jake",
      "requesterMiddleInitial": null,
      "requesterLastName": "Foster",
      "requesterPhone": "9366481127",
      "requesterPhoneExtension": null,
      "requesterPhoneOther": "2812317528",
      "requesterEmail": "xx.com",
      "jobStatusId": 0,
      "jobStatusText": null,
      "taskStatusId": 1,
      "taskStatusText": "Open",
      "taskIsOpen": true,
      "jobEttr": 2.0,
      "jobIsEstimated": false,
      "resolutionCodeId": 0,
      "resolutionCodeText": null
    }]
}